version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/schema.sql:/app/schema.sql
      - ./backend/crypto.db:/app/crypto.db # Monte la base SQLite persistante
    environment:
      - PORT=8080
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
