CREATE TABLE IF NOT EXISTS assets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key_name INTEGER NOT NULL,
    amount REAL NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    buying_price INTEGER NOT NULL,
    FOREIGN KEY (key_name) REFERENCES cryptos(key_name)
);

CREATE TABLE IF NOT EXISTS cache_prices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key_name INTEGER NOT NULL,
    price INTEGER,
    last_update DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (key_name) REFERENCES cryptos(key_name)
);

CREATE TABLE IF NOT EXISTS cryptos (
    key_name TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL
);

INSERT INTO cryptos (key_name, name) VALUES
('bitcoin', 'Bitcoin'),
('ethereum', 'Ethereum'),
('tether', 'Tether'),
('binancecoin', 'BNB'),
('usd-coin', 'USD Coin'),
('ripple', 'XRP'),
('cardano', 'Cardano'),
('dogecoin', 'Dogecoin'),
('solana', 'Solana'),
('tron', 'TRON'),
('litecoin', 'Litecoin'),
('polkadot', 'Polkadot'),
('polygon', 'Polygon'),
('shiba-inu', 'Shiba Inu'),
('dai', 'Dai'),
('wrapped-bitcoin', 'Wrapped Bitcoin'),
('uniswap', 'Uniswap'),
('avalanche', 'Avalanche'),
('chainlink', 'Chainlink'),
('leo-token', 'LEO Token'),
('cosmos', 'Cosmos'),
('the-open-network', 'Toncoin'),
('monero', 'Monero'),
('stellar', 'Stellar'),
('okb', 'OKB'),
('bitcoin-cash', 'Bitcoin Cash'),
('trueusd', 'TrueUSD'),
('filecoin', 'Filecoin'),
('internet-computer', 'Internet Computer'),
('hedera', 'Hedera'),
('lido-dao', 'Lido DAO'),
('arbitrum', 'Arbitrum'),
('aptos', 'Aptos'),
('quant-network', 'Quant'),
('cronos', 'Cronos'),
('vechain', 'VeChain'),
('algorand', 'Algorand'),
('maker', 'Maker'),
('elrond', 'MultiversX'),
('the-sandbox', 'The Sandbox'),
('eos', 'EOS'),
('immutable-x', 'Immutable X'),
('aave', 'Aave'),
('decentraland', 'Decentraland'),
('tezos', 'Tezos'),
('theta-token', 'Theta Network'),
('axie-infinity', 'Axie Infinity'),
('fantom', 'Fantom'),
('stacks', 'Stacks'),
('flow', 'Flow'),
('neo', 'NEO'),
('huobi-token', 'Huobi Token'),
('kucoin-shares', 'KuCoin Token'),
('sui', 'Sui'),
('curve-dao-token', 'Curve DAO'),
('gmx', 'GMX'),
('bitdao', 'BitDAO'),
('convex-finance', 'Convex Finance'),
('rocket-pool', 'Rocket Pool'),
('frax', 'Frax'),
('thorchain', 'THORChain'),
('paxos-standard', 'Pax Dollar'),
('pancakeswap', 'PancakeSwap'),
('usdd', 'USDD'),
('zcash', 'Zcash'),
('iota', 'IOTA'),
('render-token', 'Render'),
('kaspa', 'Kaspa'),
('loopring', 'Loopring'),
('1inch', '1inch'),
('enjincoin', 'Enjin Coin'),
('mina-protocol', 'Mina Protocol'),
('bittorrent', 'BitTorrent'),
('gala', 'Gala'),
('floki', 'Floki'),
('gemini-dollar', 'Gemini Dollar'),
('nexo', 'NEXO'),
('trust-wallet-token', 'Trust Wallet Token'),
('stepn', 'STEPN'),
('mask-network', 'Mask Network'),
('compound-governance-token', 'Compound'),
('baby-doge-coin', 'Baby Doge Coin'),
('holotoken', 'Holo'),
('optimism', 'Optimism'),
('decred', 'Decred'),
('ravencoin', 'Ravencoin'),
('theta-fuel', 'Theta Fuel'),
('oasis-network', 'Oasis Network'),
('bitcoin-sv', 'Bitcoin SV'),
('tether-gold', 'Tether Gold'),
('just', 'JUST'),
('dash', 'Dash'),
('balancer', 'Balancer'),
('kusama', 'Kusama');

INSERT INTO cache_prices (key_name, price) VALUES
('bitcoin', 75200),    
('ethereum', 2950),     
('tether', 0.93),     
('binancecoin', 205),      
('usd-coin', 0.50),     
('ripple', 0.61),     
('cardano', 5.90),     
('dogecoin', 0.07),     
('solana', 23.50),    
('tron', 164.00),  
('litecoin', 550.00),  
('polkadot', 0.85),    
('polygon', 88.00),   
('shiba-inu', 0.45),    
('dai', 6.80),    
('wrapped-bitcoin', 4.20),    
('uniswap', 0.07),    
('avalanche', 23.50),   
('chainlink', 164.00),  
('leo-token', 550.00),  
('cosmos', 0.85),    
('the-open-network', 88.00),   
('monero', 0.45),    
('stellar', 6.80),    
('okb', 4.20),    
('bitcoin-cash', 0.07),    
('trueusd', 23.50),   
('filecoin', 164.00),  
('internet-computer', 550.00),  
('hedera', 0.85),    
('lido-dao', 88.00),   
('arbitrum', 0.45),    
('aptos', 6.80),    
('quant-network', 4.20),    
('cronos', 0.07),    
('vechain', 23.50),   
('algorand', 164.00),  
('maker', 550.00),  
('elrond', 0.85),    
('the-sandbox', 88.00),   
('eos', 0.45),    
('immutable-x', 6.80),    
('aave', 4.20),    
('decentraland', 0.07),    
('tezos', 23.50),   
('theta-token', 164.00),  
('axie-infinity', 550.00),  
('fantom', 0.85),    
('stacks', 88.00),   
('flow', 0.45),    
('neo', 6.80),    
('huobi-token', 4.20),    
('kucoin-shares', 0.07),    
('sui', 23.50),   
('curve-dao-token', 164.00),  
('gmx', 550.00),  
('bitdao', 0.85),    
('convex-finance', 88.00),   
('rocket-pool', 0.45),    
('frax', 6.80),    
('thorchain', 4.20),    
('paxos-standard', 0.07),    
('pancakeswap', 23.50),   
('usdd', 164.00),  
('zcash', 550.00),  
('iota', 0.85),    
('render-token', 88.00),   
('kaspa', 0.45),    
('loopring', 6.80),    
('1inch', 4.20),    
('enjincoin', 0.07),    
('mina-protocol', 23.50),   
('bittorrent', 164.00),  
('gala', 550.00),  
('floki', 0.85),    
('gemini-dollar', 88.00),   
('nexo', 0.45),    
('trust-wallet-token', 6.80),    
('stepn', 4.20),    
('mask-network', 0.07),    
('compound-governance-token', 4.20),    
('baby-doge-coin', 0.07),    
('holotoken', 23.50),   
('optimism', 164.00),  
('decred', 550.00),  
('ravencoin', 0.85),    
('theta-fuel', 88.00),   
('oasis-network', 0.45),    
('bitcoin-sv', 6.80),    
('tether-gold', 4.20),    
('just', 0.07),    
('dash', 23.50),   
('balancer', 164.00),  
('kusama', 550.00);    



