CREATE TABLE IF NOT EXISTS assets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key_name INTEGER NOT NULL,
    amount REAL NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    purchased_price INTEGER NOT NULL,
    FOREIGN KEY (key_name) REFERENCES cryptos(key_name)
);

CREATE TABLE IF NOT EXISTS cache_prices (
    key_name TEXT PRIMARY KEY,
    price INTEGER,
    last_update DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (key_name) REFERENCES cryptos(key_name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cryptos (
    key_name TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL
);

INSERT INTO cryptos (key_name, name) VALUES
('bitcoin', 'Bitcoin'),
('ethereum', 'Ethereum'),
('tether', 'Tether'),
('binancecoin', 'BNB'),
('usd-coin', 'USD Coin'),
('ripple', 'XRP'),
('cardano', 'Cardano'),
('dogecoin', 'Dogecoin'),
('solana', 'Solana'),
('tron', 'TRON'),
('litecoin', 'Litecoin'),
('polkadot', 'Polkadot'),
('polygon', 'Polygon'),
('shiba-inu', 'Shiba Inu'),
('dai', 'Dai'),
('wrapped-bitcoin', 'Wrapped Bitcoin'),
('uniswap', 'Uniswap'),
('avalanche', 'Avalanche'),
('chainlink', 'Chainlink'),
('leo-token', 'LEO Token'),
('cosmos', 'Cosmos'),
('the-open-network', 'Toncoin'),
('monero', 'Monero'),
('stellar', 'Stellar'),
('okb', 'OKB'),
('bitcoin-cash', 'Bitcoin Cash'),
('trueusd', 'TrueUSD'),
('filecoin', 'Filecoin'),
('internet-computer', 'Internet Computer'),
('hedera', 'Hedera'),
('lido-dao', 'Lido DAO'),
('arbitrum', 'Arbitrum'),
('aptos', 'Aptos'),
('quant-network', 'Quant'),
('cronos', 'Cronos'),
('vechain', 'VeChain'),
('algorand', 'Algorand'),
('maker', 'Maker'),
('elrond', 'MultiversX'),
('the-sandbox', 'The Sandbox'),
('eos', 'EOS'),
('immutable-x', 'Immutable X'),
('aave', 'Aave'),
('decentraland', 'Decentraland'),
('tezos', 'Tezos'),
('theta-token', 'Theta Network'),
('axie-infinity', 'Axie Infinity'),
('fantom', 'Fantom'),
('stacks', 'Stacks'),
('flow', 'Flow'),
('neo', 'NEO'),
('huobi-token', 'Huobi Token'),
('kucoin-shares', 'KuCoin Token'),
('sui', 'Sui'),
('curve-dao-token', 'Curve DAO'),
('gmx', 'GMX'),
('bitdao', 'BitDAO'),
('convex-finance', 'Convex Finance'),
('rocket-pool', 'Rocket Pool'),
('frax', 'Frax'),
('thorchain', 'THORChain'),
('paxos-standard', 'Pax Dollar'),
('pancakeswap', 'PancakeSwap'),
('usdd', 'USDD'),
('zcash', 'Zcash'),
('iota', 'IOTA'),
('render-token', 'Render'),
('kaspa', 'Kaspa'),
('loopring', 'Loopring'),
('1inch', '1inch'),
('enjincoin', 'Enjin Coin'),
('mina-protocol', 'Mina Protocol'),
('bittorrent', 'BitTorrent'),
('gala', 'Gala'),
('floki', 'Floki'),
('gemini-dollar', 'Gemini Dollar'),
('nexo', 'NEXO'),
('trust-wallet-token', 'Trust Wallet Token'),
('stepn', 'STEPN'),
('mask-network', 'Mask Network'),
('compound-governance-token', 'Compound'),
('baby-doge-coin', 'Baby Doge Coin'),
('holotoken', 'Holo'),
('optimism', 'Optimism'),
('decred', 'Decred'),
('ravencoin', 'Ravencoin'),
('theta-fuel', 'Theta Fuel'),
('oasis-network', 'Oasis Network'),
('bitcoin-sv', 'Bitcoin SV'),
('tether-gold', 'Tether Gold'),
('just', 'JUST'),
('dash', 'Dash'),
('balancer', 'Balancer'),
('kusama', 'Kusama');
