package db

import "github.com/Bellzebuth/go-crypto/src/models"

var AssetsList = []models.Asset{
	{Id: "bitcoin", Name: "Bitcoin"},
	{Id: "ethereum", Name: "Ethereum"},
	{Id: "tether", Name: "Tether"},
	{Id: "binancecoin", Name: "Binance Coin"},
	{Id: "solana", Name: "Solana"},
	{Id: "ripple", Name: "XRP"},
	{Id: "cardano", Name: "Cardano"},
	{Id: "dogecoin", Name: "Dogecoin"},
	{Id: "avalanche-2", Name: "Avalanche"},
	{Id: "tron", Name: "Tron"},
	{Id: "polkadot", Name: "Polkadot"},
	{Id: "polygon", Name: "Polygon"},
	{Id: "litecoin", Name: "Litecoin"},
	{Id: "shiba-inu", Name: "Shiba Inu"},
	{Id: "bitcoin-cash", Name: "Bitcoin Cash"},
	{Id: "stellar", Name: "Stellar"},
	{Id: "chainlink", Name: "Chainlink"},
	{Id: "uniswap", Name: "Uniswap"},
	{Id: "cosmos", Name: "Cosmos"},
	{Id: "monero", Name: "Monero"},
	{Id: "ethereum-classic", Name: "Ethereum Classic"},
	{Id: "filecoin", Name: "Filecoin"},
	{Id: "internet-computer", Name: "Internet Computer"},
	{Id: "hedera", Name: "Hedera"},
	{Id: "quant-network", Name: "Quant"},
	{Id: "vechain", Name: "VeChain"},
	{Id: "apecoin", Name: "ApeCoin"},
	{Id: "algorand", Name: "Algorand"},
	{Id: "tezos", Name: "Tezos"},
	{Id: "the-graph", Name: "The Graph"},
}
